"""Initial

Revision ID: 1fa88c556efb
Revises: 
Create Date: 2024-04-02 03:04:15.200880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa88c556efb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('bybit_secret', sa.String(length=200), nullable=False),
    sa.Column('bybit_key', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bybit_key'),
    sa.UniqueConstraint('bybit_secret')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('api', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api'], ['api.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('api')
    # ### end Alembic commands ###
