"""Initial

Revision ID: c596bf91dcd7
Revises: 
Create Date: 2024-04-04 05:47:19.170559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c596bf91dcd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('bybit_secret', sa.String(), nullable=False),
    sa.Column('bybit_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bybit_key'),
    sa.UniqueConstraint('bybit_secret')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('api', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api'], ['api.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('stg_dict', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy')
    op.drop_table('users')
    op.drop_table('api')
    # ### end Alembic commands ###
